### ISSUE TITLE
Bootstrapping Regular Bloomfilter from a Redis Bloomfilter

### ISSUE THREAD

**Issue by rahul-amaram-vizury** [Baqend/Orestes-Bloomfilter#11]
Hi,
I have a quick query. Let us say I have a Redis Bloomfilter to which I keep adding entries, which in turn updates Redis.

Now is it possible for me to bootstrap a Regular Bloom filter by fetching this data from Redis? If so, how do I do it?

Thanks,
Rahul.

**Comment by DivineTraube** [comment]
Hi,

sorry for the long delay! There now is a simple way to do it: both the RedisBloomFilter and the RedisCountingBloomFilter support a toMemoryFilter method https://rawgit.com/Baqend/Orestes-Bloomfilter/1.02/dist/doc/index.html

Best,
Felix
