### ISSUE TITLE
maven issue - invalid SHA1

### ISSUE THREAD

**Issue by sundriver** [Baqend/Orestes-Bloomfilter#16]
Hi There,
 Nice work !

 The following error is stopping me from referencing this project in maven:

problem while downloading module descriptor: https://raw.githubusercontent.com/Baqend/Orestes-Bloomfilter/master/maven-repo/com/baqend/bloom-filter/1.0/bloom-filter-1.0.pom: invalid sha1: expected=b112c77d6d14e915f8149240616de0e3c4299a5c computed=4d559b5ae487f5e3ec492659f46a669b5e2dd768

I am getting this error for v1.0, 1.01 and 1.02. 

Would be nice if you can look into this

**Comment by DivineTraube** [comment]
Hi,

we were unable to reproduce this - could you retry with the newest release?

Thanks,
Felix

**Comment by DivineTraube** [comment]
For now, I think we can consider this done, as the build process changed a lot. If the problem reoccurs, we can reopen this issue.
