### ISSUE TITLE
Java 7 backport of your code

### ISSUE THREAD

**Issue by Crystark** [Baqend/Orestes-Bloomfilter#18]
Hi,

I've just finished backporting your code to java 7. Take a look at my branch [port-java7](https://github.com/Crystark/Orestes-Bloomfilter).
I can't suggest a pull request to a new branch on your side (there's no option in github for that) but I thought you might like to have it and it seems you could do this using command line.

The only discrepancies are the tests that used `CompletableFuture` which I haven't rewritten for java 7.
Otherwise all tests pass. I haven't yet built it but I wanted to share this work early as it's already on github.

I think this may be usefull to people who can't yet afford to switch to Java 8.
Please let me know what you think about it.

**Comment by DivineTraube** [comment]
Thanks a lot for this great work! I'm sure this will be interesting for a lot of people. We created a link in the docs pointing to your backport.
