### ISSUE TITLE
Will there be full of race conditions for redis backend?

### ISSUE THREAD

**Issue by purplepapa** [Baqend/Orestes-Bloomfilter#19]
Please refer to:
https://github.com/jmhodges/opposite_of_a_bloom_filter/issues/3

**Comment by DivineTraube** [comment]
Hi, no, it will of course not be, as our multi-threaded tests demonstrate. It was not easy to get it right, but it's perfectly possible.
https://github.com/jmhodges/opposite_of_a_bloom_filter/issues/3
