### ISSUE TITLE
Provide a shared Redis Pool to a Bloom Filter?

### ISSUE THREAD

**Issue by ChrisCurtin** [Baqend/Orestes-Bloomfilter#27]
Hi,

Is there a way to provide a shared connection pool to a set of BloomFilters instead of creating one each time in the BloomFilterRedis constructor?

We're seeing almost double the time to add items to a BloomFilter if we have to create a new one each time. 

Our use case is to have many thousands of filters, and based on incoming events figure out which filter to add and query. So creating a new pool for possibly 1 time use defeats having a pool.

Thanks,

Chris

**Comment by DivineTraube** [comment]
Hi,

added this an option to the FilterBuilder in release 1.1.1. Using pool(myPool) you can now reuse an existing pool which you can get from an existing filter by calling redisBF.config().pool();

Best,
Felix

**Comment by ChrisCurtin** [comment]
Hi,

Thanks for the quick reply, except I've found 2 issues:
1. the new setter is named 'password(RedisPool pool)' which I suspect is a mistake :)
2. the call to the new pool() method in the Builder is only implemented in the counting bloom filter, but we're using a regular filter. It still is building the pool explicitly in the constructor (BloomFilterRedis)

Thanks,

Chris

**Comment by DivineTraube** [comment]
Hi,

you're right of course. Added a test and made a new release. This should work now:

        BloomFilter<String> bf = createFilter("pooltest", 10_000, 0.01);
        RedisPool pool = bf.config().pool();
        FilterBuilder clonedConfig = bf.config().clone().name("pooltest-cloned");
        BloomFilter<String> filter = counts ? clonedConfig.buildCountingBloomFilter() : clonedConfig.buildBloomFilter();
        filter.add("filter");
        bf.add("bf");
        assertTrue(filter.contains("filter"));
        assertTrue(bf.contains("bf"));
        assertFalse(filter.contains("bf"));
        assertSame(pool, filter.config().pool());

Best,
Felix

**Comment by ChrisCurtin** [comment]
Hi,

Thanks for fixing this. I'm now seeing something really strange with a remote Redis if the key in Redis for the filter being created with a pool already exists.

Steps:
- flushall in Redis
- run the script below, it will run through all cases, including passing the correct hostname on to the third filter created.
- run the script again. Note that the host is now localhost, and then we can't connect to a remote database.
- flushall in Redis
- repeat running the code twice and it will work the first time, but not the second.

 public static void main(String[] args) {

        BloomFilter<String> bf = new FilterBuilder(1000000, 0.001)
                .name("temp")
                .redisBacked(true)
                .redisHost("vrd01.atlnp1")
                .redisConnections(10)
                .buildBloomFilter();

        boolean contains = bf.contains("0");
        if (contains) System.out.println("Had it");
        else System.out.println("Doesn't have it");
        
        BloomFilter<String> bf1 = new FilterBuilder(1000, 0.001)
                .name("temp2")
                .redisBacked(true)
                .redisHost("vrd01.atlnp1")
                .buildBloomFilter();
        contains = bf1.add("0");
        if (!contains) System.out.println("1 Had it");
        else System.out.println("1 Doesn't have it");

        RedisPool pool = bf1.config().pool();
        System.out.println(pool.getHost());
        
        BloomFilter<String> bf2 = new FilterBuilder(1000000, 0.001)
                .name("second")
                .redisBacked(true)
                .pool(pool)
                .buildBloomFilter();
        
        contains = bf2.contains("0");
        if (contains) System.out.println("2 Had it");
        else System.out.println("2 Doesn't have it");
    }
