### ISSUE TITLE
build a redis-bloom-filter from a json is not supported

### ISSUE THREAD

**Issue by hqw19881118** [Baqend/Orestes-Bloomfilter#29]
Hi, now I need to build a redis-bloom-filter from a json(converted from another bloom-filter), but I have not found a way to set. 
I just find getBitSet() method but not setBitSet(BitSet bitSet) method, and I test that letting getRedisBitSet() be **public** in **BloomFilterRedis** can satisfy my demand. e.g.
`bloomFilter.getRedisBitSet().overwriteBitSet(BitSet.valueOf(bits));`
so, could you please make it public in the future versions ?
thank you.

**Comment by DivineTraube** [comment]
BloomFilterMemory has a public setBitSet method which accepts a BitSet and set the reference to be used in the instance.
