### ISSUE TITLE
Adding Population Count, looking for implementation advice

### ISSUE THREAD

**Issue by ChrisCurtin** [Baqend/Orestes-Bloomfilter#5]
Hi,

We have added a population count to the regular and Redis-backed bloom filters, but before submitting a pull request wanted to get direction on where this feature should be added.

The changes add a field or Redis key for the population, meaning the unique number of items added to the filter, understanding that the error percent is also reflected in the population counts.

For the first iteration, we've added derived classes for this capability with minor changes to the existing classes. The changes are mostly around figuring out which add calls actually changed bits in the filter. 

The most invasive part was adding another method for a bulk add, since addAll today does not return a status to tell us which items were added.

However looking at the implementation we think enhancing the BloomFilters classes would be a better/cleaner way of supporting a population count vs. a derived class. In particular the Redis classes had to change some visibility on methods to allow access to the internal Jedis which made me think this should be in the existing classes.

Can you give us direction on whether or not to implement this directly in the existing classes or keep it external? (For Redis, I figured I could have a flag to NOT do the population unless explicitly created to do it, so as to not have the extra round trip)

Thanks,

Chris

**Comment by DivineTraube** [comment]
Hi, did you have a look at the new counting features? They seem to exhibit really good performance on Redis, so I guess we will stick with the BITCOUNT approach.

Best,
Felix
