### ISSUE TITLE
Error when building with gradle

### ISSUE THREAD

**Issue by zachanon** [Baqend/Orestes-Bloomfilter#62]
I am getting a plugin error when trying to build

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/zach/sources/Orestes-Bloomfilter/build.gradle' line: 4
> 
> * What went wrong:
> Plugin [id: 'com.jfrog.bintray', version: '1.1'] was not found in any of the following sources:
> 
> - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> - Plugin Repositories (could not resolve plugin artifact 'com.jfrog.bintray:com.jfrog.bintray.gradle.plugin:1.1')
>   Searched in the following repositories:
>     Gradle Central Plugin Repository
> 

I tried changing the version to v1.8.5 and got the same error

some more info

> ------------------------------------------------------------
> Gradle 6.8.3
> ------------------------------------------------------------
> 
> Build time:   2021-02-22 16:13:28 UTC
> Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78
> 
> Kotlin:       1.4.20
> Groovy:       2.5.12
> Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
> JVM:          11.0.10 (Ubuntu 11.0.10+9-Ubuntu-0ubuntu1.18.04)
> OS:           Linux 5.4.0-70-generic amd64
> 
>

**Comment by mndfcked** [comment]
If you use IntelliJ IDEA, please make sure that you're not in offline mode. More information an that [here](https://www.jetbrains.com/help/idea/working-offline.html#gradle). If that's not the case you can try to comment out the the corresponding lines (4 & 90-109) in the build.gradle file. The plugin is still available in the [Gradle Core Plugins repository](https://plugins.gradle.org/plugin/com.jfrog.bintray/1.1).

**Comment by zachanon** [comment]
I'm running 'gradle build' in the project directory from a terminal.

Something is probably weird with gradle on my end, as after following your advice I got a similar error

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/zach/sources/Orestes-Bloomfilter/build.gradle' line: 5
> 
> * What went wrong:
> Plugin [id: 'net.researchgate.release', version: '2.6.0'] was not found in any of the following sources:
> 
> - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> - Plugin Repositories (could not resolve plugin artifact 'net.researchgate.release:net.researchgate.release.gradle.plugin:2.6.0')
>   Searched in the following repositories:
>     Gradle Central Plugin Repository

Tried to comment out the second plugin and got

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/zach/sources/Orestes-Bloomfilter/build.gradle' line: 76
> 
> * What went wrong:
> A problem occurred evaluating root project 'bloom-filter'.
> > Could not find method release() for arguments [build_a7tb7rkm8p5fu2m2nacde2qt6$_run_closure10@4d67f242] on root project 'bloom-filter' of type org.gradle.api.Project.

Any ideas as to what's going wrong?

(for more info as to why I'm building from source, I wanted to implement a 'learned' bloom filter as in this paper https://arxiv.org/abs/1712.01208 so I figured it would be most useful to start with an already working bloom filter library.)

Thanks for any help and advice here.

**Comment by zachanon** [comment]
So the issue was maven is finicky about proxies. I had to edit a settings.xml file to allow it to download the plugins.

**Comment by mndfcked** [comment]
Glad to hear you could find the issue.
